name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Sulabh
      - name: log greeting time
        run: echo '${{steps.greet.outputs.time}}'
      - name:

